### ISSUE TITLE
Nodetype property definition - Opera 0.6.4 

### ISSUE THREAD

**Issue by AlexSpart** [radon-h2020/xopera-opera#14]
Following issue #13,

I modified the csar so that the` TOSCA-Meta-File-Version: 1.1` is defined in the TOSCA.meta file but I run into the following error:
`_definitions/radonblueprints__ServerlessToDoListAPI.tosca:91:7: [NodeTemplate] Missing a required property: name. If the property is optional please specify this in the definition with 'required: false' or supply its default value using 'default: <value>'.`
This refers to the definition of a `type: radon.nodes.aws.AwsDynamoDBTable` node and the csar I used is exported from the latest radon-particles.

Another example of this error is the following: `_definitions/radonblueprints__ThumbnailGeneration.tosca:28:7: [NodeTemplate] Missing a required property: maxsize. If the property is optional please specify this in the definition with 'required: false' or supply its default value using 'default: <value>'.` 
This refers to the definition of a `type: radon.nodes.aws.AwsS3Bucket` node and the csar I used is exported from the latest radon-particles.

This is a known to me error, as it was introduced with opera 0.6.3. Are we waiting for a PR on radon-particles defining the affected nodetype properties @miwurster or is this an issue from opera side @anzoman?

**Comment by anzoman** [comment]
@AlexSpart with opera version 0.6.3 TOSCA properties became [required by default](https://github.com/xlab-si/xopera-opera/issues/131) as the standard says. So, you either have to set `required: false` for optional properties or you can supply their default value. I think that your errors may happen because some properties don't have their default values (or don't have `required` keyname set to `false`).

**Comment by miwurster** [comment]
We had a short discussion on Slack lately. From what I saw, the `maxsize` property is defined on the TOSCA node normative type `ObjectStorage`. AFAIK the normative TOSCA types are kinda built into xOpera.
I think setting some arbitrary value for the respective `AwsS3Bucket` node templates (the `AwsS3Bucket` are derived from `ObjectStorage`) should solve the problem. Alternatively, overwriting the `maxsize` property on the `AwsS3Bucket` with a default value could also help.

@AlexSpart as an intermediate solution I would suggest you try to set some arbitrary values for these required properties. The value doesn't matter in this case as the Ansible implementation already work w/o them.

**Comment by v-yussupov** [comment]
Just an addition to what @miwurster mentioned, the `maxsize` property is not required in the TOSCA normative type definition:

![image](https://user-images.githubusercontent.com/10276774/105056038-04e8bd80-5a74-11eb-83ed-e9c4afdca58d.png)

**Comment by miwurster** [comment]
Good catch @v-yussupov.
@anzoman what is your point of view? Are these types built into xOpera and can be fixed respectively?

**Comment by cankarm** [comment]
Normative types are built-in, yes. We will need to fix that.

**Comment by anzoman** [comment]
@miwurster yes, normative types are somehow "built" into opera. As the standard says - when you use `tosca_definitions_version` line in your TOSCA service template, the orchestrator
> automatically imports (without the use of an explicit import statement) the normative type definitions (e.g., Node, Relationship, Capability, Artifact, etc.) that are associated with the TOSCA Simple Profile Specification the TOSCA Namespace Alias value identifies."

So, when running with opera all TOSCA properties are now required by default (also the ones that are from normative types). From what I see `tosca.nodes.Storage.ObjectStorage` normative type might has an error in its definition. The `maxsize` property is described to be optional so `required` keyname on that property should be explicitly set to `false` or there should be a default value specified. But none of that is present in the type's definition:

![image](https://user-images.githubusercontent.com/41727816/105189123-ed253e00-5b34-11eb-8109-bf7648d9971f.png)

This means that opera treats `maxsize` as a required property because we use the normative type definition from the picture above. All in all, we can resolve this by adding `required: false` to `tosca.nodes.Storage.ObjectStorage` normative node type.

**Comment by cankarm** [comment]
Thanks, @anzoman. That's interesting. So probably it would be necessary to point out this at some TOSCA meeting?

However,  we should add `required: false`  in the normative type and explained in a comment that in the TOSCA standard definition this line is missing. As above in a table, there is clearly stated that `maxsize` is not required.

**Comment by anzoman** [comment]
@cankarm yes we can mention this. They might forget to update it for the upcoming `2.0` version as well which is not good. I believe that there are also some other minor inconsistencies throughout the standard - this is also one I found randomly some time ago https://github.com/xlab-si/xopera-opera/issues/53 and it could be also mentioned to the TOSCA Committee.

As for our fix I will prepare the necessary PR (and issue) and will let others know when this is done within xOpera.

**Comment by anzoman** [comment]
Hi everyone, the `ObjectStorage` TOSCA normative type has been corrected within opera (with https://github.com/xlab-si/xopera-opera/pull/167). Please verify that the deployment now works.

**Comment by duelle** [comment]
I can confirm the initial reported issue with `radon.nodes.aws.AwsDynamoDBTable` with latest particles and opera v0.6.4.
Looks like the inherited properties from `tosca.nodes.Database` are assumed to be required.
```
$ opera deploy ServerlessToDoListAPI.csar 
_definitions/radonblueprints__ServerlessToDoListAPI.tosca:91:7: [NodeTemplate] Missing a required property: name. If the property is optional please specify this in the definition with 'required: false' or supply its default value using 'default: <value>'.
```
After adding the name, it asks for port/password/.. etc.

**Comment by miwurster** [comment]
Which is fine for the `name` property I think...

But according to the spec, port, user, and password are not set to be required. So, there shouldn't be an error message.

**Comment by anzoman** [comment]
@duelle and @miwurster yes only the `name` TOSCA property is marked as required for `tosca.nodes.Database` normative node type and therefore `opera` should only ask for this if not provided. 

![image](https://user-images.githubusercontent.com/41727816/107336329-3ffd7000-6ab9-11eb-9e89-04001847ee4a.png)

But again I think that we found a mistake in the type's definition (similar to the one in https://github.com/xlab-si/xopera-opera/issues/166). So, this is a YAML definition for `tosca.nodes.Database` normative node type:

```yaml
tosca.nodes.Database:
  derived_from: tosca.nodes.Root
  properties:
    name:
      type: string
      description: the logical name of the database
    port:
      type: integer
      description: the port the underlying database service will listen to for data
    user:
      type: string
      description: the optional user account name for DB administration
      required: false
    password:
      type: string
      description: the optional password for the DB user account
      required: false
  requirements:
    - host:
        capability: tosca.capabilities.Compute
        node: tosca.nodes.DBMS
        relationship: tosca.relationships.HostedOn
  capabilities:
    database_endpoint:
      type: tosca.capabilities.Endpoint.Database
```

As you can see the `port` property is not marked with `required: false` and neither it has a default value assigned, which means that (according to the TOSCA standard) it will be treated as a required property and `opera` will moan if you don't assign that value. For `user` and `password` properties the definition seems ok and `opera` shouldn't treat them as required. To sum up, to fix this we can add `required: false` to the `port` property definition within `opera`. 

cc @cankarm this is another thing that could be  mentioned to the TOSCA Committee at some TOSCA meeting.

**Comment by duelle** [comment]
I tried to fix the said issue locally by setting the properties of Database to `required: false`, but still after exporting I get asked for a port value. Are the base types (e.g., Database) of TOSCA not taken into account when exported or are they overridden by internal versions included in Opera itself?

```
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  tosca.nodes.Database:
    derived_from: tosca.nodes.Root
    metadata:
      targetNamespace: "tosca.nodes"
      abstract: "false"
      final: "false"
    properties:
      password:
        type: string
        description: the optional password for the DB user account
        required: false
      port:
        type: integer
        description: the port the underlying database service will listen to for data
        required: false
      name:
        type: string
        description: the logical name of the database
      user:
        type: string
        description: the optional user account name for DB administration
        required: false
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          node: tosca.nodes.DBMS
          relationship: tosca.relationships.HostedOn
          occurrences: [ 1, 1 ]
    capabilities:
      database_endpoint:
        occurrences: [ 1, UNBOUNDED ]
        type: tosca.capabilities.Endpoint.Database
```

Error message:
`_definitions/radonblueprints__ServerlessToDoListAPI.tosca:91:7: [NodeTemplate] Missing a required property: port. If the property is optional please specify this in the definition with 'required: false' or supply its default value using 'default: <value>'.`
