### ISSUE TITLE
Storing/caching information between deploy and undeploy

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#2]
When deploying with opera, we use a certain file being placed in a folder known at deploy-time. What would be the intended/best way to store the path to that file to be used in the undeploy step?

Example deployment like stated in https://github.com/radon-h2020/demo-ctt-sockshop/blob/master/radon-ctt/create.yml
- create temporary folder
- copy artifact (e.g., docker-compose.yml) to temporary folder on target machine
- use that artifact for deployment

Undeployment:
- Undeploy services using the same docker-compose.yml file

How would/should I store information like the path to the docker-compose.yml file from the deploy step to be able to use it in the undeploy step?

**Comment by cankarm** [comment]
It's a bit unclear what would you like to achieve, the link seems corrupted. 

xOpera deploys application through yaml. It also undeploys it, just with calling "opera undeploy". Surely the deploy and un-deploy playbooks must exist and be properly written. xOpera stores _all deploy information required for undeploy_. Sure, if there is something specific, when you need an IP, etc. You must collect this data through deploy using playbooks, ansible "register" function, etc.

**Comment by duelle** [comment]
Here's the fixed link: https://github.com/radon-h2020/demo-ctt-sockshop/blob/master/radon-ctt/create_sut.yml
The property that I would like to store is the 
> temp_dir.path

so I know where the docker-compose.yml can be found to be able to issue a docker-compose stop or docker-compose rm

**Comment by cankarm** [comment]
Ok, I think that now I understand what you would like to achieve. I think that you need "set_stats" task.

An example we can follow is " createRole" and in particular "role_arn" parameter. See the yaml of toy example [here](
https://github.com/radon-h2020/demo-tosca-blueprint-aws-lambda/blob/master/resize_service_opera_v1_3.yml) and corresponding playbook for role is [here](https://github.com/radon-h2020/demo-tosca-blueprint-aws-lambda/blob/master/playbooks/aws_role/create.yml).  In the playbook find the "set_stats" task. This task stores the property in xOpera for later and make it available to other modules also. But it needs to be defined/initialised in the module also.

Does this solve your issue?

**Comment by duelle** [comment]
I added the `set_stats` module similar to the example you provided.

```- name: Run SockShop
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create temporary directory for the related artifacts
      tempfile:
        state: directory
        prefix: radon-ctt-opera_
      register: temp_dir

    - name: copy docker-compose to the temporary directory
      copy:
        src: docker-compose.yml
        dest: "{{ temp_dir.path }}/docker-compose.yml"

    - name: run docker-compose from shell
      shell: docker-compose -f "{{ temp_dir.path }}/docker-compose.yml" up -d front-end edge-router catalogue catalogue-db carts carts-db orders orders-db shipping queue-master rabbitmq payment user user-db

    - name: Store path to docker-compose.yml file
      set_stats:
        data:
          docker_compose_path: "{{ temp_dir.path }}/docker-compose.yml"
        per_host: yes
```


Would I use the opera output feature to get the value out and feed it to the undeploy step somehow or can I pick that value up in the delete.yml directly?

**Comment by cankarm** [comment]
you should be able to pick it up in delete.yml - if it is initialized in the inputs before that delete.yml operation it should work,

**Comment by anzoman** [comment]
Hi, I would like to leave a comment. The proposed solution with set_stats could work but I never tested it for two seuqential operations (e.g create and then delete). I remember that we used set_stats for the deployment part with create operation so that data which were actually TOSCA attributes could be passed through different node type operations within Ansible playbooks. But I am not sure that this is also meant for passing stored information when you switch from deploy to undeploy.

However, you could solve this by defining a new node type operation called `delete` which will be invoked when you call `opera undeploy`. Then you can pass the new Ansible playbook  (for instance named like delete.yml or remove.yml) as primary implementation  which will get executed during the undeploy phase. To access `docker-compose.yml` from that playbook you should use `dependencies` which will assure that you will be able to use the specified docker-compose file for stopping or removing your containers whenever you will call undeploy.

Your WebApplication node type from TOSCA template could look like this:

```
node_types:
  radon.nodes.docker.WebApplication:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        operations:
          create:
            implementation:
              primary: create_sut.yml
              dependencies:
                - ../deploy/docker-compose/docker-compose.yml
          delete:
            implementation:
              primary: delete_sut.yml
              dependencies:
                - ../deploy/docker-compose/docker-compose.yml
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
```

And I also have a question here for @duelle . Do you really need `docker-compose.yml` for the undeploy part? If I remember correctly you can just run `docker-compose down` and all the containers that were created by docker-compose up command will be stopped and removed. Please correct me if I'm wrong.

**Comment by duelle** [comment]
@anzoman 
> And I also have a question here for @duelle . Do you really need `docker-compose.yml` for the undeploy part? If I remember correctly you can just run `docker-compose down` and all the containers that were created by docker-compose up command will be stopped and removed. Please correct me if I'm wrong.

Yes, the `docker-compose.yml` is needed for the undeployment. If it is not provided, `docker-compose` complains that it does not know what to do.

In the end all I want to achieve is to be able to store one (or several) variable between the executions of the deploy and the undeploy step of opera. In this case, I would like to store the dynamically created path to the docker-compose.yml on the target machine so I do not have to repetitively copy the same file over and prevent conflicts due to hard-coded paths.

**Comment by anzoman** [comment]
Aha now I get it. So to store variable between the executions and to be able to pass it between TOSCA types (nodes, relationships, capabilities...) you will need to use `set_stats` Anisble module in one of your playbooks. Let me provide the example to clearify this.

For example if you have a node type defined like this:

```
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  nodes.test.first:
    derived_from: tosca.nodes.SoftwareComponent
    attributes:
      something_to_pass_on:
        type: string
        description: Test for passing data between nodes
        default: "just something to be passed on"
    interfaces:
      Standard:
        inputs:
          something_to_pass_on: {default: { get_attribute: [SELF, something_to_pass_on] }, type: string}
        operations:
          create: playbooks/create.yml
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
```
You can see that I defined an attribute which will be used for passing on the string value of a variable called `something_to_pass_on`. It is mandatory to define shared variables as TOSCA attributed because attributes are in general used to expose the actual state of some property of a TOSCA entity after it has been deployed and instantiated by the TOSCA orchestrator (xOpera). Another important thing is that you cannot set this attribute from playbook without declaring an input with the same name (it can also have a different name) and setting it by default to attribute's value which you can get using `get_attribute` function. Because inputs are those who can be used as Ansible vars in templating.

So in playbook you can then set the attribute like this:

```
- hosts: all
  gather_facts: false
  tasks:
    - name: Set attributes for the second node
      set_stats:
        data:
          something_to_pass_on: "{{ something_to_pass_on }}"
```

So the variable has been set and you can use it freely in the second node like this:

```
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  nodes.test.second:
    derived_from: tosca.nodes.Root
    interfaces:
      Standard:
        inputs:
          receive_something: {default:  {get_attribute: [SELF, receives_notification, something_to_pass_on] }, type: string }
        operations:
          create: playbooks/create.yml
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
      - receives_notification:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.DependsOn
```

Make sure to define the notification in node requirements which will link it to the previous node and you will be able to access the attributes from the first node. You can then define an input (`receive_something`) where you use that requirement (`receives_notification`) to collect the value. And the corresponding playbook:

```
- hosts: all
  gather_facts: false
  tasks:
    - name: Print out the received value
      debug:
        msg: "Here is my received value: {{ receive_something }}"
```

So maybe you can store and pass on the variable with path to the docker-compose.yml. Does that seem ok to you? Let me know if you have any further questions.
