### ISSUE TITLE
Access deployment IP-addresses via opera

### ISSUE THREAD

**Issue by duelle** [radon-h2020/xopera-opera#4]
After having deployed using a service template (e.g., https://github.com/radon-h2020/demo-ctt-sockshop/blob/master/radon-ctt/ti.yml ), I want to obtain the actual public IP address of the deployment to access it from remote.
I tried using the intrinsic functions of TOSCA with the opera outputs, but apparently didn't find the
correct way on how to get the property that holds the actual IP address
of the deployed service. 
How would one do that properly?

**Comment by cankarm** [comment]
I think that the answer of this question is answered already here #3 . 

Please confirm if this is correct.

**Comment by duelle** [comment]
If I get you correctly, one would get the IP address from Ansible vars and store it with `set_stats` and output that variable with the opera outputs?

**Comment by cankarm** [comment]
Yes? Or I may not get you how you actually want to obtain IP. Who tells you which IP some VM has?

**Comment by anzoman** [comment]
Maybe you can use opera outputs (like [here](https://github.com/xlab-si/xopera-opera/blob/master/examples/outputs/service.yaml)) and do something like that:

```
tosca_definitions_version: tosca_simple_yaml_1_3

node_types:
  radon.nodes.docker.WebApplication:
    derived_from: tosca.nodes.SoftwareComponent
    interfaces:
      Standard:
        operations:
          create:
            implementation:
              primary: create_ti.yml
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn

topology_template:
  node_templates:
    Workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost

    JMeterAgent:
      type: radon.nodes.docker.WebApplication
      requirements:
        - host: Workstation

  outputs:
    deployment_public_address:
      description: Public adress attribute output
      value: { get_attribute: [ Workstation, public_address ] }
```

Then you can retrieve outputs by running `opera outputs`. But this would be accessible from the machine where you started the deployment and not from the remote machine deployed on.
