### ISSUE TITLE
Missing definition for `tosca.capabilities.EndPoint`

### ISSUE THREAD

**Issue by miwurster** [radon-h2020/xopera-opera#6]
Hi, when we try to use a Service Template using an `EndPoint` capability (which is a normative type), xOpera returns with the following message:

`radonnodesdocker__DockerApplication.tosca:19:23: [ReferenceWrapper] Invalid reference capability_types/tosca.capabilities.EndPoint`

Seems that the `tosca.capabilities.EndPoint` normative type is missing.

See also this issue https://github.com/radon-h2020/radon-gmt/issues/22

**Comment by anzoman** [comment]
Hi, xOpera orchestrator supports `tosca.capabilities.Endpoint`. It seems to me that you have a typo because it is `Endpoint` not `EndPoint` (take a look here: [tosca.capabilities.Endpoint](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html#DEFN_TYPE_CAPABILITIES_ENDPOINT))

I tried to pass an example TOSCA service template to xOpera that includes a capability which derives from `tosca.capabilities.Endpoint`.

This below is an example of the service template:

```
tosca_definitions_version: tosca_simple_yaml_1_3

capability_types:
  radon.capabilities.Test:
    derived_from: tosca.capabilities.Endpoint

node_types:
  radon.nodes.Test:
    derived_from: tosca.nodes.Root
    requirements:
      - host:
          capability: tosca.capabilities.Compute
          relationship: tosca.relationships.HostedOn
      - test_capability:
          capability: radon.capabilities.Test
          relationship: tosca.relationships.DependsOn

topology_template:
  node_templates:
    my_workstation:
      type: tosca.nodes.Compute

    test:
      type: radon.nodes.Test
```

And this is the result of deploying with opera:

![deploy](https://user-images.githubusercontent.com/41727816/79545590-38d02600-8091-11ea-8076-085cc7b6a61a.png)

Does that solve your problems?
